### ISSUE TITLE
Etcd Unavailable when bootstrapping with vagrant

### ISSUE THREAD

**Issue by rosskukulinski** [paz-sh/paz#43]
I ran into an issue when bootstrapping a vagrant coreos cluster with paz.  Specifically, when running the script ```install-vagrant.sh```, etcd was not available in time.

As a hack, I added a 5 second sleep right before launchAndWaitForUnits which "fixed" the issue on my machine.

**Comment by lukebond** [comment]
@rosskukulinski sorry for delay in responding!

I'm currently unable to repro the issue you have, on Linux or OSX. Are you still seeing it?

If I understand you correctly, you're saying that within the Vagrant cluster the install script was trying to do something before Etcd happened to be ready, hence adding the delay fixed it? If so we should look into a test that waits until Etcd is ready before it proceeds.

**Comment by lukebond** [comment]
Going to call this fixed because the move to Etcd2 has changed a lot of things in this area. Startup is much more stable now.
